### ISSUE TITLE
how to open this RUDY_short/3-RISCY-a-1-c2-u0.7-m1-p3-f0" 

### ISSUE THREAD

**Issue by chuangzhidan** [ycchen218/DRC-Prediction#1]
hi ,how to open this file?
"data/RUDY_short/3-RISCY-a-1-c2-u0.7-m1-p3-f0"

**Comment by ycchen218** [comment]
Hi, @chuangzhidan 
     Use np.load(data/RUDY_short/3-RISCY-a-1-c2-u0.7-m1-p3-f0), you can find an example in drc_predict.py data_process() function. The result will look like the figure below.
![image](https://github.com/ycchen218/EDA-DRC-Prediction/assets/130541072/5eeb459f-1de2-4f28-8599-ef8a4574e5bc)
